import type { SlidePlan } from "./outline";
import {
  PRIMARY,
  ACCENT,
  TEXT_DARK,
  DECK_LAYOUT,
  DECK_TITLE_BOX,
  DECK_SUBTITLE_BOX,
  DECK_SLIDE_TITLE_BOX,
  DECK_BULLETS_BOX,
} from "./layout";

// The freeform, Canva-style data model: a deck is a plain array of slides, every slide a
// plain array of positioned elements - no more special-cased "title slide" type. AI
// generation and templates still speak the older, simpler {title, bullets} shape
// (SlidePlan, from outline.ts) because that's a far more reliable schema to get an LLM to
// produce than raw coordinates - slideFromPlan below is the one place that shape becomes
// real, independently draggable/resizable elements, seeded at the same positions
// lib/presentation/layout.ts already defines so a freshly generated or templated deck
// looks identical to the old fixed layout until the user actually moves something.

export type TextAlign = "left" | "center" | "right";
export const FONT_FAMILIES = ["Arial", "Georgia", "Verdana", "Times New Roman", "Trebuchet MS", "Courier New"] as const;
export type FontFamily = (typeof FONT_FAMILIES)[number];

export interface BaseElement {
  id: string;
  xIn: number;
  yIn: number;
  wIn: number;
  hIn: number;
}

/** `role` marks an element as "the thing AI rewrite updates" (see DeckEditor.tsx's
 * extractPlanFromSlide/applyPlanToSlide) - freeform elements added by the user (a text
 * box, a shape, an image, a table) have no role and are left untouched by AI rewrite. */
export interface TextElement extends BaseElement {
  type: "text";
  role?: "title" | "body";
  text: string;
  fontSize: number;
  color: string;
  fontFamily?: FontFamily;
  bold?: boolean;
  italic?: boolean;
  align?: TextAlign;
}

export interface ShapeElement extends BaseElement {
  type: "shape";
  shape: "rect" | "ellipse";
  fill: string;
  /** 0-100, defaults to 100 (fully opaque) - what makes the overlapping-circle "designed
   * cover graphic" look (see decorativeAccents below) possible without needing actual
   * photography, which this app has no legitimate way to source. */
  opacity?: number;
}

export interface ImageElement extends BaseElement {
  type: "image";
  dataUrl: string;
}

export interface TableElement extends BaseElement {
  type: "table";
  rows: string[][];
  headerRow?: boolean;
}

export type SlideElement = TextElement | ShapeElement | ImageElement | TableElement;

export interface Slide {
  id: string;
  background: string;
  elements: SlideElement[];
  /** Speaker notes - exported via PptxGenJS's addNotes (lib/presentation/renderDeck.ts),
   * never shown on the slide itself. */
  notes?: string;
}

let counter = 0;
export function newId(): string {
  counter += 1;
  return `el_${Date.now().toString(36)}_${counter}`;
}

function cloneElement(el: SlideElement): SlideElement {
  return { ...el, id: newId() };
}

/** A tasteful abstract cover graphic - a handful of overlapping, semi-transparent
 * circles in the deck's own two brand colors. This is what "good-looking pictures" on
 * every generated cover slide means here: a real, native, infinitely-crisp PowerPoint
 * shape composition (fully editable/movable afterward like any other element), not a
 * fake stock photo - this app has no licensed image library or stock-photo API to draw
 * a real one from. */
export function decorativeAccents(primary: string, accent: string): ShapeElement[] {
  return [
    { id: newId(), type: "shape", shape: "ellipse", fill: accent, opacity: 22, xIn: 6.9, yIn: -1.2, wIn: 4.5, hIn: 4.5 },
    { id: newId(), type: "shape", shape: "ellipse", fill: "FFFFFF", opacity: 12, xIn: 8.2, yIn: 2.6, wIn: 3, hIn: 3 },
    { id: newId(), type: "shape", shape: "ellipse", fill: primary, opacity: 35, xIn: -1.5, yIn: 3.6, wIn: 4, hIn: 4 },
  ];
}

/** The auto-generated first page of a new deck - same visual as the old fixed "title
 * slide" (renderDeck.ts's original hardcoded first addSlide call), now just an ordinary
 * Slide made of a decorative shape composition plus two text elements. */
export function titleSlide(title: string, primary: string = PRIMARY, accent: string = ACCENT): Slide {
  return {
    id: newId(),
    background: primary,
    elements: [
      ...decorativeAccents(primary, accent),
      {
        id: newId(),
        type: "text",
        role: "title",
        text: title,
        xIn: DECK_TITLE_BOX.xIn,
        yIn: DECK_TITLE_BOX.yIn,
        wIn: DECK_TITLE_BOX.wIn,
        hIn: DECK_TITLE_BOX.hIn,
        fontSize: DECK_TITLE_BOX.fontSize,
        color: "FFFFFF",
        bold: true,
      },
      {
        id: newId(),
        type: "text",
        text: "Generated by Homie Presentation",
        xIn: DECK_SUBTITLE_BOX.xIn,
        yIn: DECK_SUBTITLE_BOX.yIn,
        wIn: DECK_SUBTITLE_BOX.wIn,
        hIn: DECK_SUBTITLE_BOX.hIn,
        fontSize: DECK_SUBTITLE_BOX.fontSize,
        color: accent,
      },
    ],
  };
}

/** One content slide from a {title, bullets} plan - the title and the bullets (joined as
 * one multi-line text box, same as a normal Canva body text box rather than N separate
 * draggable bullet objects) each become one role-tagged TextElement, plus a small corner
 * accent bar so content slides don't look bare next to the decorated cover. */
export function slideFromPlan(plan: SlidePlan, primary: string = PRIMARY, accent: string = ACCENT): Slide {
  return {
    id: newId(),
    background: "FFFFFF",
    elements: [
      { id: newId(), type: "shape", shape: "rect", fill: primary, xIn: 0, yIn: 0, wIn: 0.12, hIn: DECK_LAYOUT.heightIn },
      { id: newId(), type: "shape", shape: "ellipse", fill: accent, opacity: 60, xIn: 9.55, yIn: -0.35, wIn: 0.9, hIn: 0.9 },
      {
        id: newId(),
        type: "text",
        role: "title",
        text: plan.title,
        xIn: DECK_SLIDE_TITLE_BOX.xIn,
        yIn: DECK_SLIDE_TITLE_BOX.yIn,
        wIn: DECK_SLIDE_TITLE_BOX.wIn,
        hIn: DECK_SLIDE_TITLE_BOX.hIn,
        fontSize: DECK_SLIDE_TITLE_BOX.fontSize,
        color: primary,
        bold: true,
      },
      {
        id: newId(),
        type: "text",
        role: "body",
        text: plan.bullets.map((b) => `• ${b}`).join("\n"),
        xIn: DECK_BULLETS_BOX.xIn,
        yIn: DECK_BULLETS_BOX.yIn,
        wIn: DECK_BULLETS_BOX.wIn,
        hIn: DECK_BULLETS_BOX.hIn,
        fontSize: DECK_BULLETS_BOX.fontSize,
        color: TEXT_DARK,
      },
    ],
  };
}

export function deckFromPlans(title: string, plans: SlidePlan[], primary: string = PRIMARY, accent: string = ACCENT): Slide[] {
  return [titleSlide(title, primary, accent), ...plans.map((p) => slideFromPlan(p, primary, accent))];
}

/** A brand-new blank slide, for DeckEditor.tsx's "+ Add slide" - just enough to not be
 * empty (one title-role text box) so it isn't a totally inert page. */
export function blankSlide(): Slide {
  return {
    id: newId(),
    background: "FFFFFF",
    elements: [
      {
        id: newId(),
        type: "text",
        role: "title",
        text: "New slide",
        xIn: DECK_SLIDE_TITLE_BOX.xIn,
        yIn: DECK_SLIDE_TITLE_BOX.yIn,
        wIn: DECK_SLIDE_TITLE_BOX.wIn,
        hIn: DECK_SLIDE_TITLE_BOX.hIn,
        fontSize: DECK_SLIDE_TITLE_BOX.fontSize,
        color: PRIMARY,
        bold: true,
      },
    ],
  };
}

/** Deep-clones a slide with fresh element ids, for DeckEditor.tsx's "Duplicate slide". */
export function duplicateSlide(slide: Slide): Slide {
  return { ...slide, id: newId(), elements: slide.elements.map(cloneElement) };
}

/** Clones one element with a fresh id and a small position offset, so the copy is
 * visible next to the original instead of stacked exactly on top of it - DeckEditor.tsx's
 * "Duplicate element". */
export function duplicateElement(el: SlideElement): SlideElement {
  return { ...cloneElement(el), xIn: el.xIn + 0.25, yIn: el.yIn + 0.25 };
}

/** A freeform text box the user inserts via DeckEditor.tsx's "+ Text" button - deliberately
 * has no `role`, so AI rewrite (which only touches role-tagged elements) never touches it. */
export function newTextBox(): TextElement {
  return {
    id: newId(),
    type: "text",
    text: "New text",
    xIn: 3,
    yIn: 2.3,
    wIn: 4,
    hIn: 1,
    fontSize: 20,
    color: TEXT_DARK,
  };
}

export function newShape(): ShapeElement {
  return { id: newId(), type: "shape", shape: "rect", fill: ACCENT, xIn: 3.5, yIn: 2, wIn: 3, hIn: 2 };
}

export function newTable(): TableElement {
  return {
    id: newId(),
    type: "table",
    headerRow: true,
    rows: [
      ["Column A", "Column B", "Column C"],
      ["", "", ""],
      ["", "", ""],
    ],
    xIn: 1.5,
    yIn: 1.8,
    wIn: 7,
    hIn: 2,
  };
}

/** Sizes a new image element to fit within a max box while preserving its real aspect
 * ratio, rather than stretching every upload into a fixed square. */
export function newImage(dataUrl: string, naturalWidth: number, naturalHeight: number): ImageElement {
  const maxWIn = 5;
  const maxHIn = 3.5;
  const aspect = naturalWidth / naturalHeight || 1;
  let wIn = maxWIn;
  let hIn = wIn / aspect;
  if (hIn > maxHIn) {
    hIn = maxHIn;
    wIn = hIn * aspect;
  }
  return {
    id: newId(),
    type: "image",
    dataUrl,
    xIn: (DECK_LAYOUT.widthIn - wIn) / 2,
    yIn: (DECK_LAYOUT.heightIn - hIn) / 2,
    wIn,
    hIn,
  };
}

/** Moves one element forward/backward in the render/stacking order (array order = layer
 * order, last = frontmost) - DeckEditor.tsx's "Bring forward"/"Send backward". */
export function reorderElement(elements: SlideElement[], id: string, direction: "forward" | "backward" | "front" | "back"): SlideElement[] {
  const index = elements.findIndex((el) => el.id === id);
  if (index === -1) return elements;
  const next = [...elements];
  const [el] = next.splice(index, 1);
  if (direction === "front") next.push(el);
  else if (direction === "back") next.unshift(el);
  else if (direction === "forward") next.splice(Math.min(index + 1, next.length), 0, el);
  else next.splice(Math.max(index - 1, 0), 0, el);
  return next;
}

/** Reads the current title/body text back out of a slide's role-tagged elements, for
 * sending to the billed AI-rewrite route (which still speaks the simpler {title,
 * bullets} shape) - null if the user deleted those elements entirely, in which case
 * DeckEditor hides the AI-rewrite control rather than send a nonsensical request. */
export function extractPlanFromSlide(slide: Slide): SlidePlan | null {
  const titleEl = slide.elements.find((el): el is TextElement => el.type === "text" && el.role === "title");
  const bodyEl = slide.elements.find((el): el is TextElement => el.type === "text" && el.role === "body");
  if (!titleEl) return null;
  const bullets = (bodyEl?.text ?? "")
    .split("\n")
    .map((line) => line.replace(/^[•\-*]\s*/, "").trim())
    .filter(Boolean);
  return { title: titleEl.text, bullets: bullets.length > 0 ? bullets : ["..."] };
}

/** Inverse of extractPlanFromSlide - writes an AI-rewritten {title, bullets} back into
 * the slide's existing title/body elements in place, so their position/size/color/style
 * (and any other freeform elements on the slide) survive the rewrite untouched. */
export function applyPlanToSlide(slide: Slide, plan: SlidePlan): Slide {
  return {
    ...slide,
    elements: slide.elements.map((el) => {
      if (el.type !== "text") return el;
      if (el.role === "title") return { ...el, text: plan.title };
      if (el.role === "body") return { ...el, text: plan.bullets.map((b) => `• ${b}`).join("\n") };
      return el;
    }),
  };
}
