import type { SlidePlan } from "./outline";
import {
  PRIMARY,
  ACCENT,
  TEXT_DARK,
  DECK_LAYOUT,
  DECK_TITLE_BOX,
  DECK_SUBTITLE_BOX,
  DECK_SLIDE_TITLE_BOX,
  DECK_BULLETS_BOX,
} from "./layout";

// The freeform, Canva-style data model: a deck is a plain array of slides, every slide a
// plain array of positioned elements - no more special-cased "title slide" type. AI
// generation and templates still speak the older, simpler {title, bullets} shape
// (SlidePlan, from outline.ts) because that's a far more reliable schema to get an LLM to
// produce than raw coordinates - slideFromPlan below is the one place that shape becomes
// real, independently draggable/resizable elements, seeded at the same positions
// lib/presentation/layout.ts already defines so a freshly generated or templated deck
// looks identical to the old fixed layout until the user actually moves something.

export type TextAlign = "left" | "center" | "right";

export interface BaseElement {
  id: string;
  xIn: number;
  yIn: number;
  wIn: number;
  hIn: number;
}

/** `role` marks an element as "the thing AI rewrite updates" (see DeckEditor.tsx's
 * extractPlanFromSlide/applyPlanToSlide) - freeform elements added by the user (a text
 * box, a shape, an image) have no role and are left untouched by AI rewrite. */
export interface TextElement extends BaseElement {
  type: "text";
  role?: "title" | "body";
  text: string;
  fontSize: number;
  color: string;
  bold?: boolean;
  italic?: boolean;
  align?: TextAlign;
}

export interface ShapeElement extends BaseElement {
  type: "shape";
  shape: "rect" | "ellipse";
  fill: string;
}

export interface ImageElement extends BaseElement {
  type: "image";
  dataUrl: string;
}

export type SlideElement = TextElement | ShapeElement | ImageElement;

export interface Slide {
  id: string;
  background: string;
  elements: SlideElement[];
}

let counter = 0;
export function newId(): string {
  counter += 1;
  return `el_${Date.now().toString(36)}_${counter}`;
}

/** The auto-generated first page of a new deck - same visual as the old fixed "title
 * slide" (renderDeck.ts's original hardcoded first addSlide call), now just an ordinary
 * Slide made of two text elements. */
export function titleSlide(title: string): Slide {
  return {
    id: newId(),
    background: PRIMARY,
    elements: [
      {
        id: newId(),
        type: "text",
        role: "title",
        text: title,
        xIn: DECK_TITLE_BOX.xIn,
        yIn: DECK_TITLE_BOX.yIn,
        wIn: DECK_TITLE_BOX.wIn,
        hIn: DECK_TITLE_BOX.hIn,
        fontSize: DECK_TITLE_BOX.fontSize,
        color: "FFFFFF",
        bold: true,
      },
      {
        id: newId(),
        type: "text",
        text: "Generated by Homie Presentation",
        xIn: DECK_SUBTITLE_BOX.xIn,
        yIn: DECK_SUBTITLE_BOX.yIn,
        wIn: DECK_SUBTITLE_BOX.wIn,
        hIn: DECK_SUBTITLE_BOX.hIn,
        fontSize: DECK_SUBTITLE_BOX.fontSize,
        color: ACCENT,
      },
    ],
  };
}

/** One content slide from a {title, bullets} plan - the title and the bullets (joined as
 * one multi-line text box, same as a normal Canva body text box rather than N separate
 * draggable bullet objects) each become one role-tagged TextElement. */
export function slideFromPlan(plan: SlidePlan): Slide {
  return {
    id: newId(),
    background: "FFFFFF",
    elements: [
      {
        id: newId(),
        type: "text",
        role: "title",
        text: plan.title,
        xIn: DECK_SLIDE_TITLE_BOX.xIn,
        yIn: DECK_SLIDE_TITLE_BOX.yIn,
        wIn: DECK_SLIDE_TITLE_BOX.wIn,
        hIn: DECK_SLIDE_TITLE_BOX.hIn,
        fontSize: DECK_SLIDE_TITLE_BOX.fontSize,
        color: PRIMARY,
        bold: true,
      },
      {
        id: newId(),
        type: "text",
        role: "body",
        text: plan.bullets.map((b) => `• ${b}`).join("\n"),
        xIn: DECK_BULLETS_BOX.xIn,
        yIn: DECK_BULLETS_BOX.yIn,
        wIn: DECK_BULLETS_BOX.wIn,
        hIn: DECK_BULLETS_BOX.hIn,
        fontSize: DECK_BULLETS_BOX.fontSize,
        color: TEXT_DARK,
      },
    ],
  };
}

export function deckFromPlans(title: string, plans: SlidePlan[]): Slide[] {
  return [titleSlide(title), ...plans.map(slideFromPlan)];
}

/** A brand-new blank slide, for DeckEditor.tsx's "+ Add slide" - just enough to not be
 * empty (one title-role text box) so it isn't a totally inert page. */
export function blankSlide(): Slide {
  return {
    id: newId(),
    background: "FFFFFF",
    elements: [
      {
        id: newId(),
        type: "text",
        role: "title",
        text: "New slide",
        xIn: DECK_SLIDE_TITLE_BOX.xIn,
        yIn: DECK_SLIDE_TITLE_BOX.yIn,
        wIn: DECK_SLIDE_TITLE_BOX.wIn,
        hIn: DECK_SLIDE_TITLE_BOX.hIn,
        fontSize: DECK_SLIDE_TITLE_BOX.fontSize,
        color: PRIMARY,
        bold: true,
      },
    ],
  };
}

/** A freeform text box the user inserts via DeckEditor.tsx's "+ Text" button - deliberately
 * has no `role`, so AI rewrite (which only touches role-tagged elements) never touches it. */
export function newTextBox(): TextElement {
  return {
    id: newId(),
    type: "text",
    text: "New text",
    xIn: 3,
    yIn: 2.3,
    wIn: 4,
    hIn: 1,
    fontSize: 20,
    color: TEXT_DARK,
  };
}

export function newShape(): ShapeElement {
  return { id: newId(), type: "shape", shape: "rect", fill: ACCENT, xIn: 3.5, yIn: 2, wIn: 3, hIn: 2 };
}

/** Sizes a new image element to fit within a max box while preserving its real aspect
 * ratio, rather than stretching every upload into a fixed square. */
export function newImage(dataUrl: string, naturalWidth: number, naturalHeight: number): ImageElement {
  const maxWIn = 5;
  const maxHIn = 3.5;
  const aspect = naturalWidth / naturalHeight || 1;
  let wIn = maxWIn;
  let hIn = wIn / aspect;
  if (hIn > maxHIn) {
    hIn = maxHIn;
    wIn = hIn * aspect;
  }
  return {
    id: newId(),
    type: "image",
    dataUrl,
    xIn: (DECK_LAYOUT.widthIn - wIn) / 2,
    yIn: (DECK_LAYOUT.heightIn - hIn) / 2,
    wIn,
    hIn,
  };
}

/** Reads the current title/body text back out of a slide's role-tagged elements, for
 * sending to the billed AI-rewrite route (which still speaks the simpler {title,
 * bullets} shape) - null if the user deleted those elements entirely, in which case
 * DeckEditor hides the AI-rewrite control rather than send a nonsensical request. */
export function extractPlanFromSlide(slide: Slide): SlidePlan | null {
  const titleEl = slide.elements.find((el): el is TextElement => el.type === "text" && el.role === "title");
  const bodyEl = slide.elements.find((el): el is TextElement => el.type === "text" && el.role === "body");
  if (!titleEl) return null;
  const bullets = (bodyEl?.text ?? "")
    .split("\n")
    .map((line) => line.replace(/^[•\-*]\s*/, "").trim())
    .filter(Boolean);
  return { title: titleEl.text, bullets: bullets.length > 0 ? bullets : ["..."] };
}

/** Inverse of extractPlanFromSlide - writes an AI-rewritten {title, bullets} back into
 * the slide's existing title/body elements in place, so their position/size/color/style
 * (and any other freeform elements on the slide) survive the rewrite untouched. */
export function applyPlanToSlide(slide: Slide, plan: SlidePlan): Slide {
  return {
    ...slide,
    elements: slide.elements.map((el) => {
      if (el.type !== "text") return el;
      if (el.role === "title") return { ...el, text: plan.title };
      if (el.role === "body") return { ...el, text: plan.bullets.map((b) => `• ${b}`).join("\n") };
      return el;
    }),
  };
}
