import PptxGenJS from "pptxgenjs";
import type { SlidePlan } from "./outline";

// Stage 5 from the product spec: pure code, no AI call - the model only ever produces the
// SlidePlan[] JSON (lib/outline.ts), never layout or OOXML. This is the architectural
// split that prevents the overflow/overlap/misalignment failure mode of purely AI-driven
// slide generators; it's also why this function takes no model input at all.
//
// Applies a fixed, single default design system (Homie's own brand colors) rather than
// extracting one from an uploaded template - Stage 2 (design-from-template/description/
// reference-images) isn't built yet in this vertical slice. Swapping in a real Design
// System JSON later only means this function reads colors/fonts from that instead of
// these constants; the render loop itself doesn't change shape.

const PRIMARY = "005C3D"; // Homie brand dark green
const ACCENT = "F8B712"; // Homie brand gold
const TEXT_DARK = "101914";

export async function renderDeck(slides: SlidePlan[], title: string): Promise<Buffer> {
  const pres = new PptxGenJS();
  pres.defineLayout({ name: "HOMIE_16X9", width: 10, height: 5.63 });
  pres.layout = "HOMIE_16X9";

  const titleSlide = pres.addSlide();
  titleSlide.background = { color: PRIMARY };
  titleSlide.addText(title, {
    x: 0.6,
    y: 2.0,
    w: 8.8,
    h: 1.4,
    fontSize: 36,
    bold: true,
    color: "FFFFFF",
    fontFace: "Arial",
  });
  titleSlide.addText("Generated by Homie Presentation", {
    x: 0.6,
    y: 3.4,
    w: 8.8,
    h: 0.5,
    fontSize: 14,
    color: ACCENT,
    fontFace: "Arial",
  });

  for (const slide of slides) {
    const s = pres.addSlide();
    s.background = { color: "FFFFFF" };
    s.addText(slide.title, {
      x: 0.5,
      y: 0.4,
      w: 9,
      h: 0.9,
      fontSize: 28,
      bold: true,
      color: PRIMARY,
      fontFace: "Arial",
    });
    s.addText(
      slide.bullets.map((b) => ({ text: b, options: { bullet: true, breakLine: true } })),
      {
        x: 0.6,
        y: 1.5,
        w: 8.8,
        h: 3.7,
        fontSize: 18,
        color: TEXT_DARK,
        fontFace: "Arial",
        valign: "top",
        lineSpacingMultiple: 1.3,
      },
    );
  }

  return (await pres.write({ outputType: "nodebuffer" })) as Buffer;
}
